modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/JensenJ-Modding/Architectury-Template/issues"
license = "MIT License"

[[mods]]
modId = "architecturymod"
version = "${version}"
displayName = "Architectury Mod"
authors = "JensenJ - Developer"
description = '''
Mod Description
'''

[[dependencies.architecturymod]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.architecturymod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.architecturymod]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"