modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/JensenJ-Modding/MC-Server-Test/issues"
license = "MIT License"

[[mods]]
modId = "mcservertest"
version = "${version}"
displayName = "MC Server Test"
authors = "JensenJ - Developer"
description = '''
A simple mod which will stop a minecraft server after x seconds to produce an exit code of 0 for testing mods with GitHub actions.
'''

[[dependencies.mcservertest]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mcservertest]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"